# Generated by Django 3.2.23 on 2023-12-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('tariff_zone', models.CharField(max_length=100, verbose_name='Тарифная зона')),
            ],
            options={
                'verbose_name': 'Станции',
                'verbose_name_plural': 'Станция',
                'ordering': ['station_name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=100, verbose_name='Номер поезда')),
                ('type', models.CharField(max_length=100, verbose_name='Тип поезда')),
                ('carriage_number', models.IntegerField(verbose_name='Число вагонов')),
            ],
            options={
                'verbose_name': 'Поезд',
                'verbose_name_plural': 'Поезда',
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время отправления')),
                ('end_time', models.TimeField(verbose_name='Время прибытия')),
                ('pass_station', models.CharField(max_length=1000, verbose_name='Станции без остановки')),
                ('end_station',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_end_station',
                                   to='trains.station', verbose_name='Станция окончания маршрута')),
                ('start_station',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_start_station',
                                   to='trains.station', verbose_name='Станция начала маршрута')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train',
                                            verbose_name='Поезд')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['start_time'],
            },
        ),
    ]
